package ca.thepopbox;

import java.util.ArrayList;
import java.util.List;

public class LegoColorData {

    // Method to lookup LegoColor by its name
    public static LegoColor getColorByName(String colorName) {
        for (LegoColor color : getAllColors()) {
            if (color.getName().equalsIgnoreCase(colorName)) { // Case-insensitive comparison
                return color;
            }
        }
        return null; // Return null if no match is found
    }

    public static List<LegoColor> getAllColors() {
        List<LegoColor> colors = new ArrayList<>();
        colors.add(new LegoColor("White", 1));
        colors.add(new LegoColor("Very Light Gray", 49));
        colors.add(new LegoColor("Very Light Bluish Gray", 99));
        colors.add(new LegoColor("Light Bluish Gray", 86));
        colors.add(new LegoColor("Light Gray", 9));
        colors.add(new LegoColor("Dark Gray", 10));
        colors.add(new LegoColor("Dark Bluish Gray", 85));
        colors.add(new LegoColor("Black", 11));
        colors.add(new LegoColor("Dark Red", 59));
        colors.add(new LegoColor("Red", 5));
        colors.add(new LegoColor("Reddish Orange", 167));
        colors.add(new LegoColor("Dark Salmon", 231));
        colors.add(new LegoColor("Salmon", 25));
        colors.add(new LegoColor("Coral", 220));
        colors.add(new LegoColor("Light Salmon", 26));
        colors.add(new LegoColor("Sand Red", 58));
        colors.add(new LegoColor("Dark Brown", 120));
        colors.add(new LegoColor("Umber", 168));
        colors.add(new LegoColor("Brown", 8));
        colors.add(new LegoColor("Reddish Brown", 88));
        colors.add(new LegoColor("Light Brown", 91));
        colors.add(new LegoColor("Medium Brown", 240));
        colors.add(new LegoColor("Fabuland Brown", 106));
        colors.add(new LegoColor("Dark Tan", 69));
        colors.add(new LegoColor("Tan", 2));
        colors.add(new LegoColor("Light Nougat", 90));
        colors.add(new LegoColor("Medium Tan", 241));
        colors.add(new LegoColor("Nougat", 28));
        colors.add(new LegoColor("Medium Nougat", 150));
        colors.add(new LegoColor("Dark Nougat", 225));
        colors.add(new LegoColor("Sienna", 169));
        colors.add(new LegoColor("Fabuland Orange", 160));
        colors.add(new LegoColor("Earth Orange", 29));
        colors.add(new LegoColor("Dark Orange", 68));
        colors.add(new LegoColor("Rust", 27));
        colors.add(new LegoColor("Neon Orange", 165));
        colors.add(new LegoColor("Orange", 4));
        colors.add(new LegoColor("Medium Orange", 31));
        colors.add(new LegoColor("Light Orange", 32));
        colors.add(new LegoColor("Bright Light Orange", 110));
        colors.add(new LegoColor("Warm Yellowish Orange", 172));
        colors.add(new LegoColor("Very Light Orange", 96));
        colors.add(new LegoColor("Dark Yellow", 161));
        colors.add(new LegoColor("Yellow", 3));
        colors.add(new LegoColor("Light Yellow", 33));
        colors.add(new LegoColor("Bright Light Yellow", 103));
        colors.add(new LegoColor("Neon Yellow", 236));
        colors.add(new LegoColor("Lemon", 171));
        colors.add(new LegoColor("Neon Green", 166));
        colors.add(new LegoColor("Light Lime", 35));
        colors.add(new LegoColor("Yellowish Green", 158));
        colors.add(new LegoColor("Medium Lime", 76));
        colors.add(new LegoColor("Lime", 34));
        colors.add(new LegoColor("Fabuland Lime", 248));
        colors.add(new LegoColor("Olive Green", 155));
        colors.add(new LegoColor("Dark Olive Green", 242));
        colors.add(new LegoColor("Dark Green", 80));
        colors.add(new LegoColor("Green", 6));
        colors.add(new LegoColor("Bright Green", 36));
        colors.add(new LegoColor("Medium Green", 37));
        colors.add(new LegoColor("Light Green", 38));
        colors.add(new LegoColor("Sand Green", 48));
        colors.add(new LegoColor("Dark Turquoise", 39));
        colors.add(new LegoColor("Light Turquoise", 40));
        colors.add(new LegoColor("Aqua", 41));
        colors.add(new LegoColor("Light Aqua", 152));
        colors.add(new LegoColor("Dark Blue", 63));
        colors.add(new LegoColor("Blue", 7));
        colors.add(new LegoColor("Dark Azure", 153));
        colors.add(new LegoColor("Little Robots Blue", 247));
        colors.add(new LegoColor("Maersk Blue", 72));
        colors.add(new LegoColor("Medium Azure", 156));
        colors.add(new LegoColor("Sky Blue", 87));
        colors.add(new LegoColor("Medium Blue", 42));
        colors.add(new LegoColor("Bright Light Blue", 105));
        colors.add(new LegoColor("Light Blue", 62));
        colors.add(new LegoColor("Sand Blue", 55));
        colors.add(new LegoColor("Dark Blue-Violet", 109));
        colors.add(new LegoColor("Violet", 43));
        colors.add(new LegoColor("Blue-Violet", 97));
        colors.add(new LegoColor("Lilac", 245));
        colors.add(new LegoColor("Medium Violet", 73));
        colors.add(new LegoColor("Light Lilac", 246));
        colors.add(new LegoColor("Light Violet", 44));
        colors.add(new LegoColor("Dark Purple", 89));
        colors.add(new LegoColor("Purple", 24));
        colors.add(new LegoColor("Light Purple", 93));
        colors.add(new LegoColor("Medium Lavender", 157));
        colors.add(new LegoColor("Lavender", 154));
        colors.add(new LegoColor("Clikits Lavender", 227));
        colors.add(new LegoColor("Sand Purple", 54));
        colors.add(new LegoColor("Magenta", 71));
        colors.add(new LegoColor("Dark Pink", 47));
        colors.add(new LegoColor("Medium Dark Pink", 94));
        colors.add(new LegoColor("Bright Pink", 104));
        colors.add(new LegoColor("Pink", 23));
        colors.add(new LegoColor("Rose Pink", 56));
        colors.add(new LegoColor("Trans-Clear", 12));
        colors.add(new LegoColor("Trans-Brown", 13));
        colors.add(new LegoColor("Trans-Black", 251));
        colors.add(new LegoColor("Trans-Red", 17));
        colors.add(new LegoColor("Trans-Neon Orange", 18));
        colors.add(new LegoColor("Trans-Orange", 98));
        colors.add(new LegoColor("Trans-Light Orange", 164));
        colors.add(new LegoColor("Trans-Neon Yellow", 121));
        colors.add(new LegoColor("Trans-Yellow", 19));
        colors.add(new LegoColor("Trans-Neon Green", 16));
        colors.add(new LegoColor("Trans-Bright Green", 108));
        colors.add(new LegoColor("Trans-Light Green", 221));
        colors.add(new LegoColor("Trans-Light Bright Green", 226));
        colors.add(new LegoColor("Trans-Green", 20));
        colors.add(new LegoColor("Trans-Dark Blue", 14));
        colors.add(new LegoColor("Trans-Medium Blue", 74));
        colors.add(new LegoColor("Trans-Light Blue", 15));
        colors.add(new LegoColor("Trans-Aqua", 113));
        colors.add(new LegoColor("Trans-Light Purple", 114));
        colors.add(new LegoColor("Trans-Medium Purple", 234));
        colors.add(new LegoColor("Trans-Purple", 51));
        colors.add(new LegoColor("Trans-Dark Pink", 50));
        colors.add(new LegoColor("Trans-Pink", 107));
        colors.add(new LegoColor("Chrome Gold", 21));
        colors.add(new LegoColor("Chrome Silver", 22));
        colors.add(new LegoColor("Chrome Antique Brass", 57));
        colors.add(new LegoColor("Chrome Black", 122));
        colors.add(new LegoColor("Chrome Blue", 52));
        colors.add(new LegoColor("Chrome Green", 64));
        colors.add(new LegoColor("Chrome Pink", 82));
        colors.add(new LegoColor("Pearl White", 83));
        colors.add(new LegoColor("Pearl Very Light Gray", 119));
        colors.add(new LegoColor("Pearl Light Gray", 66));
        colors.add(new LegoColor("Flat Silver", 95));
        colors.add(new LegoColor("Bionicle Silver", 239));
        colors.add(new LegoColor("Pearl Dark Gray", 77));
        colors.add(new LegoColor("Pearl Black", 244));
        colors.add(new LegoColor("Pearl Light Gold", 61));
        colors.add(new LegoColor("Pearl Gold", 115));
        colors.add(new LegoColor("Reddish Gold", 235));
        colors.add(new LegoColor("Bionicle Gold", 238));
        colors.add(new LegoColor("Flat Dark Gold", 81));
        colors.add(new LegoColor("Reddish Copper", 249));
        colors.add(new LegoColor("Copper", 84));
        colors.add(new LegoColor("Bionicle Copper", 237));
        colors.add(new LegoColor("Pearl Brown", 255));
        colors.add(new LegoColor("Pearl Red", 252));
        colors.add(new LegoColor("Pearl Green", 253));
        colors.add(new LegoColor("Pearl Blue", 254));
        colors.add(new LegoColor("Pearl Sand Blue", 78));
        colors.add(new LegoColor("Pearl Sand Purple", 243));
        colors.add(new LegoColor("Satin Trans-Clear", 228));
        colors.add(new LegoColor("Satin Trans-Brown", 229));
        colors.add(new LegoColor("Satin Trans-Yellow", 170));
        colors.add(new LegoColor("Satin Trans-Bright Green", 233));
        colors.add(new LegoColor("Satin Trans-Light Blue", 223));
        colors.add(new LegoColor("Satin Trans-Dark Blue", 232));
        colors.add(new LegoColor("Satin Trans-Purple", 230));
        colors.add(new LegoColor("Satin Trans-Dark Pink", 224));
        colors.add(new LegoColor("Metallic Silver", 67));
        colors.add(new LegoColor("Metallic Green", 70));
        colors.add(new LegoColor("Metallic Gold", 65));
        colors.add(new LegoColor("Metallic Copper", 250));
        colors.add(new LegoColor("Milky White", 60));
        colors.add(new LegoColor("Glow In Dark White", 159));
        colors.add(new LegoColor("Glow In Dark Opaque", 46));
        colors.add(new LegoColor("Glow In Dark Trans", 118));
        colors.add(new LegoColor("Glitter Trans-Clear", 101));
        colors.add(new LegoColor("Glitter Trans-Orange", 222));
        colors.add(new LegoColor("Glitter Trans-Neon Green", 163));
        colors.add(new LegoColor("Glitter Trans-Light Blue", 162));
        colors.add(new LegoColor("Glitter Trans-Purple", 102));
        colors.add(new LegoColor("Glitter Trans-Dark Pink", 100));
        colors.add(new LegoColor("Speckle Black-Silver", 111));
        colors.add(new LegoColor("Speckle Black-Gold", 151));
        colors.add(new LegoColor("Speckle Black-Copper", 116));
        colors.add(new LegoColor("Speckle DBGray-Silver", 117));
        return colors;
    }
}
